apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: frontend
        api: external        
    spec:
      containers:
      - image: obsidiancat/udacity-frontend
        name: frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
      restartPolicy: Always
  selector:
    matchLabels:
      service: frontend
