apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udagram-cluster
  region: us-east-1
nodeGroups:
  - name: udagram-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
